# Generated by Django 5.1.6 on 2025-03-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('userType', models.IntegerField(default=0)),
                ('msg', models.TextField()),
                ('createdDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='advertiser',
            fields=[
                ('advertiserid', models.AutoField(primary_key=True, serialize=False)),
                ('advertisername', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('emailid', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=50)),
                ('contact', models.TextField(max_length=50)),
                ('profilepic', models.ImageField(upload_to='images/')),
                ('isverified', models.IntegerField(default=0)),
                ('website', models.TextField(max_length=50, null=True)),
                ('instagramlink', models.TextField(max_length=50, null=True)),
                ('facebooklink', models.TextField(max_length=50, null=True)),
                ('linkeidlink', models.TextField(max_length=50, null=True)),
                ('registrationdate', models.TimeField(auto_now=True)),
                ('cityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.TextField(default='false', max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('budget', models.IntegerField()),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('bidstartdate', models.DateTimeField()),
                ('bidenddate', models.DateTimeField()),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('views', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('advertiserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.advertiser')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeId', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TimeField(auto_now=True)),
                ('advertiserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.advertiser')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.CreateModel(
            name='saveproject',
            fields=[
                ('saveprojectid', models.AutoField(primary_key=True, serialize=False)),
                ('advertiserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.advertiser')),
                ('projectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='stateid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.TextField(max_length=50)),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='projectsubcategory',
            fields=[
                ('projectsubcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('projectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.project')),
                ('subcategoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='subcategoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory'),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('emailid', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=50)),
                ('contact', models.TextField(max_length=50)),
                ('profilepic', models.ImageField(default='images/default.png', upload_to='images/')),
                ('createdDt', models.DateField(auto_now=True)),
                ('cityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=300)),
                ('rating', models.IntegerField()),
                ('date', models.TimeField(auto_now=True)),
                ('advertiserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.advertiser')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='projectbid',
            fields=[
                ('projectbidid', models.AutoField(primary_key=True, serialize=False)),
                ('bidamount', models.IntegerField()),
                ('biddate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('advertiserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.advertiser')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
