# Generated by Django 5.1.6 on 2025-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
