# Generated by Django 5.1.6 on 2025-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_advertiser_name_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='projectid',
        ),
    ]
