# Generated by Django 5.1.3 on 2025-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_review_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminLog',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
