# Generated by Django 5.1.3 on 2025-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='aname',
            field=models.TextField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='email',
            field=models.TextField(default='admin@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='password',
            field=models.TextField(default='a123', max_length=50),
        ),
    ]
