# Generated by Django 5.1.6 on 2025-04-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_adminlog_aname_alter_adminlog_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='aname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='password',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('receiverid', models.IntegerField()),
                ('message', models.TextField(default=True, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('createddt', models.DateField(auto_now=True)),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
