# Generated by Django 5.1.6 on 2025-04-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_adminlog_aname_alter_adminlog_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='projectid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='senderid',
            field=models.IntegerField(),
        ),
    ]
