# Generated by Django 5.1.6 on 2025-04-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_review_projectid_alter_chat_senderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='projectid',
        ),
    ]
